
export const products =[
    {
        nombre: "Trozos de Lulo",
        precio: 5000,
        stock: 5,
        descripcion: "Fruta exotica super refrescante para alegrar tu dia",
        categoria: "Trozos de fruta",
        img: "https://res.cloudinary.com/dt08n3f7k/image/upload/v1670726299/Lulo_b0mmxk.jpg",
    },
    {
        nombre: "Trozos de Mango",
        precio: 5000,
        stock: 5,
        descripcion: "Fruta dulce y deliciosa para alegrar tu dia",
        categoria: "Trozos de fruta",
        img: "https://res.cloudinary.com/dt08n3f7k/image/upload/v1670726411/Mango1_jor5wg.jpg",
    },
    {
        nombre: "Yuca",
        precio: 8000,
        stock: 8,
        descripcion: "Tuberculo fresco para acompañar tus platos",
        categoria: "Tuberculo",
        img: "https://res.cloudinary.com/dt08n3f7k/image/upload/v1670726411/Mango1_jor5wg.jpg",
    },
    {
        nombre: "Papa criolla",
        precio: 8000,
        stock: 8,
        descripcion: "Tuberculo fresco para acompañar tus platos",
        categoria: "Tubérculo",
        img: "https://res.cloudinary.com/dt08n3f7k/image/upload/v1670726411/Mango1_jor5wg.jpg",
    },
    {
        nombre: "Pulpa de Fresa",
        precio: 7000,
        stock: 7,
        descripcion: "Pulpa lista para hacer tus batidos o jugos",
        categoria: "Pulpa",
        img: "https://res.cloudinary.com/dt08n3f7k/image/upload/v1670726411/Mango1_jor5wg.jpg",
    },
    {
        nombre: "Pulpa de Guanabana",
        precio: 7000,
        stock: 7,
        descripcion: "Pulpa lista para hacer tus batidos o jugos",
        categoria: "Pulpa",
        img: "https://res.cloudinary.com/dt08n3f7k/image/upload/v1670726411/Mango1_jor5wg.jpg",
    },
]